import Head from "next/head";
import UserCard from "../component/UserCard";

export default function Home(props) {
  console.log(props.results[0]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <UserCard />
    </div>
  );
}

export async function getServerSideProps() {
  const data = await fetch("https://randomuser.me/api/?results=50");
  const results = data.json();
  return {
    props: results, // will be passed to the page component as props
  };
}
